# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_dialout_pb2 as grpc__dialout__pb2


class GRPCDialoutStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Dialout = channel.stream_unary(
        '/grpc_dialout.GRPCDialout/Dialout',
        request_serializer=grpc__dialout__pb2.DialoutMsg.SerializeToString,
        response_deserializer=grpc__dialout__pb2.DialoutResponse.FromString,
        )


class GRPCDialoutServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Dialout(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GRPCDialoutServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Dialout': grpc.stream_unary_rpc_method_handler(
          servicer.Dialout,
          request_deserializer=grpc__dialout__pb2.DialoutMsg.FromString,
          response_serializer=grpc__dialout__pb2.DialoutResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc_dialout.GRPCDialout', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
